import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "v0-clone",
  description: "Generated by v0-clone AI editor",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-100 text-black dark:bg-neutral-900 dark:text-white transition-colors`}>
        {children}
      </body>
    </html>
  );
}
